
version: "3"
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - api
      - frontend
    depends_on:
      - api
      - frontend
  api:
    build: api
    volumes:
      - "./api/data:/data"
    links:
      - db
  frontend:
    build: frontend
    volumes: 
      - "./frontend:/app"
    links:
      - api
  db:
    image: tutum/mysql:5.6
    environment:
      - ON_CREATE_DB=ttn_test_db
    env_file:
      - ./env/mysql.env
    volumes:
      - "ttn-test-db-data:/var/lib/mysql"
volumes:
  ttn-test-db-data:
