
version: "2"
services:
  api:
    build: api
    ports:
      - "1880:1880"
    volumes:
      - "./api/data:/data"
    links:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example